export enum Color {
    Aqua = 'Aqua',
    Black = 'Black',
    Blue = 'Blue',
    Fuchsia = 'Fuchsia',
    Gray = 'Gray',
    Green = 'Green',
    Lime = 'Lime',
    Maroon = 'Maroon',
    Navy = 'Navy',
    Olive = 'Olive',
    Purple = 'Purple',
    Random = 'Random',
    Red = 'Red',
    Silver = 'Silver',
    Teal = 'Teal',
    White = 'White',
    Yellow = 'Yellow',
}